export default {
  "Ability": {
    "STR": "Strength",
    "WIS": "Wisdom",
    "CON": "Constitution",
    "DEX": "Dexterity",
    "CHA": "Charisma",
    "INT": "Intelligence"
  },
  "Condition": {
    "BLINDED": "Blinded",
    "PRONE": "Prone",
    "PETRIFIED": "Petrified",
    "DEAFENED": "Deafened",
    "UNCONSCIOUS": "Unconscious",
    "CHARMED": "Charmed",
    "RESTRAINED": "Restrained",
    "INVISIBLE": "Invisible",
    "INCAPACITATED": "Incapacitated",
    "FRIGHTENED": "Frightened",
    "POISONED": "Poisoned",
    "PARALYZED": "Paralyzed",
    "STUNNED": "Stunned",
    "EXHAUSTION": "Exhaustion",
    "GRAPPLED": "Grappled"
  },
  "SubClass": {
    "BLADESINGING": "Bladesinging",
    "LAND_GRASSLAND": "Circle of the Land (Grassland)",
    "HEROISM": "Oath of Heroism",
    "GREAT_OLD_ONE": "The Great Old One",
    "DEVOTION": "Oath of Devotion",
    "CONQUEST": "Oath of Conquest",
    "DRUNKEN_MASTER": "Way of the Drunken Master",
    "DIVINATION": "School of Divination",
    "TOTEM_WARRIOR": "Path of the Totem Warrior",
    "ANCESTRAL_GUARDIAN": "Path of the Ancestral Guardian",
    "MOON": "Circle of the Moon",
    "KNOWLEDGE": "Knowledge Domain",
    "ELOQUENCE": "College of Eloquence",
    "WILD_MAGIC": "Wild Magic",
    "LURKER": "The Lurker in the Deep",
    "ONOMANCY": "Onomancy",
    "CAVALIER": "Cavalier",
    "HUNTER": "Hunter",
    "SAMURAI": "Samurai",
    "STORM_SORCERY": "Storm Sorcery",
    "RUNE_KNIGHT": "Rune Knight",
    "TRICKERY": "Trickery Domain",
    "BATTLERAGER": "Path of the Battlerager",
    "CROWN": "Oath of the Crown",
    "OPEN_HAND": "Way of the Open Hand",
    "LAND_DESERT": "Circle of the Land (Desert)",
    "ASTRAL_SELF": "Way of the Astral Self",
    "ARCHFEY": "The Archfey",
    "BATTLE_MASTER": "Battle Master",
    "ELDRITCH_KNIGHT": "Eldritch Knight",
    "FOUR_ELEMENTS": "Way of the Four Elements",
    "SHADOW_MAGIC": "Shadow Magic",
    "ABERRANT_MIND": "Aberrant Mind",
    "LAND_FOREST": "Circle of the Land (Forest)",
    "UNDYING": "The Undying",
    "HORIZON_WALKER": "Horizon Walker",
    "KENSEI": "Way of the Kensei",
    "SCOUT": "Scout",
    "NATURE": "Nature Domain",
    "OATHBREAKER": "Oathbreaker",
    "WILD_SOUL": "Path of the Wild Soul",
    "ANCIENTS": "Oath of the Ancients",
    "THIEF": "Thief",
    "DREAMS": "Circle of Dreams",
    "VALOR": "College of Valor",
    "ENCHANTMENT": "School of Enchantment",
    "DRACONIC_BLOODLINE": "Draconic Bloodline",
    "EVOCATION": "School of Evocation",
    "ZEALOT": "Path of the Zealot",
    "SWORDS": "College of Swords",
    "DEATH": "Death Domain",
    "VENGEANCE": "Oath of Vengeance",
    "LONG_DEATH": "Way of the Long Death",
    "NECROMANCY": "School of Necromancy",
    "BERSERKER": "Path of the Berserker",
    "SWARMKEEPER": "Swarmkeeper",
    "HEXBLADE": "The Hexblade",
    "TWILIGHT": "Twilight Domain",
    "ABJURATION": "School of Abjuration",
    "CHAMPION": "Champion",
    "MONSTER_SLAYER": "Monster Slayer",
    "SHADOW": "Way of Shadow",
    "PURPLE_DRAGON_KNIGHT": "Purple Dragon Knight",
    "GIANT_SOUL": "Giant Soul",
    "SHEPHERD": "Circle of the Shepherd",
    "LIGHT": "Light Domain",
    "STORM_HERALD": "Path of the Storm Herald",
    "ARCANE_ARCHER": "Arcane Archer",
    "DIVINE_SOUL": "Divine Soul",
    "LAND_SWAMP": "Circle of the Land (Swamp)",
    "ASSASSIN": "Assassin",
    "ILLUSION": "School of Illusion",
    "ARCANE_TRICKSTER": "Arcane Trickster",
    "FORGE": "Forge Domain",
    "LAND_MOUNTAIN": "Circle of the Land (Mountain)",
    "WILDFIRE": "Circle of Wildfire",
    "GLOOM_STALKER": "Gloom Stalker",
    "WHISPERS": "College of Whispers",
    "TEMPEST": "Tempest Domain",
    "CONJURATION": "School of Conjuration",
    "LAND_COAST": "Circle of the Land (Coast)",
    "LAND_UNDERDARK": "Circle of the Land (Underdark)",
    "SUN_SOUL": "Way of the Sun Soul",
    "WAR": "War Domain",
    "ARCANA": "Arcana Domain",
    "CELESTIAL": "The Celestial",
    "REVIVED": "The Revived",
    "LORE": "College of Lore",
    "SWASHBUCKLER": "Swashbuckler",
    "BEAST_MASTER": "Beast Master",
    "MASTERMIND": "Mastermind",
    "LIFE": "Life Domain",
    "LAND_ARCTIC": "Circle of the Land (Arctic)",
    "REDEMPTION": "Oath of Redemption",
    "FIEND": "The Fiend",
    "INVENTION": "School of Invention",
    "GRAVE": "Grave Domain",
    "INQUISITIVE": "Inquisitive",
    "WAR_MAGIC": "War Magic",
    "TRANSMUTATION": "School of Transmutation",
    "GLAMOUR": "College of Glamour",
    "BRUTE": "Brute"
  },
  "School": {
    "ENCHANTMENT": "Enchantment",
    "EVOCATION": "Evocation",
    "ABJURATION": "Abjuration",
    "TRANSMUTATION": "Transmutation",
    "ILLUSION": "Illusion",
    "DIVINATION": "Divination",
    "NECROMANCY": "Necromancy",
    "CONJURATION": "Conjuration"
  },
  "Shape": {
    "SQUARE": "Square",
    "CYLINDER": "Cylinder",
    "SPHERE": "Sphere",
    "LINE": "Line",
    "CUBE": "Cube",
    "CONE": "Cone"
  },
  "TimeUnit": {
    "ACTION": "Action",
    "HOUR": "Hour",
    "ROUND": "Round",
    "REACTION": "Reaction",
    "MINUTE": "Minute",
    "BONUS_ACTION": "Bonus Action",
    "INSTANTANEOUS": "Instantaneous",
    "DAY": "Day"
  },
  "Class": {
    "WARLOCK": "Warlock",
    "DRUID": "Druid",
    "PALADIN": "Paladin",
    "SORCERER": "Sorcerer",
    "FIGHTER": "Fighter",
    "BARD": "Bard",
    "WIZARD": "Wizard",
    "RANGER": "Ranger",
    "ROGUE": "Rogue",
    "CLERIC": "Cleric",
    "MONK": "Monk",
    "BARBARIAN": "Barbarian",
    "ARTIFICER": "Artificer"
  },
  "Duration": {
    "HOUR": "Hour",
    "ROUND": "Round",
    "MINUTE": "Minute",
    "INSTANTANEOUS": "Instantaneous",
    "DAY": "Day"
  },
  "Attack": {
    "RANGED": "Ranged",
    "MELEE": "Melee"
  },
  "CastingTime": {
    "ACTION": "Action",
    "HOUR": "Hour",
    "REACTION": "Reaction",
    "MINUTE": "Minute",
    "BONUS_ACTION": "Bonus Action"
  },
  "DamageType": {
    "NECROTIC": "Necrotic",
    "ACID": "Acid",
    "PIERCING": "Piercing",
    "LIGHTNING": "Lightning",
    "BLUDGEONING": "Bludgeoning",
    "PSYCHIC": "Psychic",
    "FORCE": "Force",
    "FIRE": "Fire",
    "POISON": "Poison",
    "RADIANT": "Radiant",
    "COLD": "Cold",
    "SLASHING": "Slashing",
    "THUNDER": "Thunder"
  },
  "Source": {
    "BR": "Basic Rules",
    "SCAG": "Sword Coast Adventurer's Guide",
    "EEPC": "Elemental Evil Player's Companion",
    "XGTE": "Xanathar's Guide to Everything",
    "PHB": "Player's Handbook"
  }
}